#!/bin/sh

case "$1" in
 	start)
		echo "start aesdsocket deamon"
		aesdsocket -d
		;;
  	stop)
		tmp=$(ps | grep aesdsocket)
		pid=$(echo $tmp | awk -F" " '{print $1}')
		kill $pid
		echo "stop aesdsocket deamon ($pid)"
		;;
 	restart|reload)
		"$0" stop
		"$0" start
		;;
 	*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


